### ISSUE TITLE
Missing packages 

### ISSUE THREAD

**Issue by Matheo5** [kirschem/install-rpiplay#1]
When I did cmake, there are gstreamer packages missing...
What version of raspbian lite should I use ?

**Comment by kirschem** [comment]
What version are you using right now?
What's the exact error you're getting?
Can you try `sudo apt update` and then run the script again.

**Comment by Matheo5** [comment]
I did but there is a problem with the make. Something link to the ilclient and a variable not use. 
The make stop at 70% and make my raspi crash...

**Comment by kirschem** [comment]
What version are you using right now?
What's the exact error you're getting?

**Comment by Matheo5** [comment]
I'm using Rasbian buster lite (last version of the raspberry pi imager

**Comment by Matheo5** [comment]
I already have a problem like this but i don't remember how I solved it...

**Comment by Matheo5** [comment]
I tried with debien lite Bullseye and i got this error on the cmake .. : 

rpiplay@raspberry:~/RPiPlay/build $ cmake ..
-- The C compiler identification is GNU 10.2.1
-- The CXX compiler identification is GNU 10.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenSSL: /usr/lib/arm-linux-gnueabihf/libcrypto.so (found suitable version "1.1.1n", minimum required is "1.1.1")
-- OpenMAX libraries not found, skipping compilation of Raspberry Pi renderer
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2")
-- Checking for modules 'gstreamer-1.0>=1.4;gstreamer-sdp-1.0>=1.4;gstreamer-video-1.0>=1.4;gstreamer-app-1.0>=1.4'
--   Found gstreamer-1.0, version 1.18.4
--   Found gstreamer-sdp-1.0, version 1.18.4
--   Found gstreamer-video-1.0, version 1.18.4
--   Found gstreamer-app-1.0, version 1.18.4
-- Configuring done
-- Generating done
-- Build files have been written to: /home/rpiplay/RPiPlay/build


Don't know why it didn't find OpenMax now... Is it a librairy automatic install on debian ?

**Comment by kirschem** [comment]
Don't know if it's optional. Can you still do `make`?

**Comment by Matheo5** [comment]
doesn't work neither

**Comment by kirschem** [comment]
Hmm I think you should raise this in the [RPiPlay repo](https://github.com/FD-/RPiPlay).
